/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protocol.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "protocol.pb-c.h"
void   pos_point__init
                     (PosPoint         *message)
{
  static PosPoint init_value = POS_POINT__INIT;
  *message = init_value;
}
size_t pos_point__get_packed_size
                     (const PosPoint *message)
{
  assert(message->base.descriptor == &pos_point__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pos_point__pack
                     (const PosPoint *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pos_point__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pos_point__pack_to_buffer
                     (const PosPoint *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pos_point__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PosPoint *
       pos_point__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PosPoint *)
     protobuf_c_message_unpack (&pos_point__descriptor,
                                allocator, len, data);
}
void   pos_point__free_unpacked
                     (PosPoint *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pos_point__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scan_result__init
                     (ScanResult         *message)
{
  static ScanResult init_value = SCAN_RESULT__INIT;
  *message = init_value;
}
size_t scan_result__get_packed_size
                     (const ScanResult *message)
{
  assert(message->base.descriptor == &scan_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scan_result__pack
                     (const ScanResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scan_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scan_result__pack_to_buffer
                     (const ScanResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scan_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScanResult *
       scan_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScanResult *)
     protobuf_c_message_unpack (&scan_result__descriptor,
                                allocator, len, data);
}
void   scan_result__free_unpacked
                     (ScanResult *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &scan_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pad_pass__init
                     (PadPass         *message)
{
  static PadPass init_value = PAD_PASS__INIT;
  *message = init_value;
}
size_t pad_pass__get_packed_size
                     (const PadPass *message)
{
  assert(message->base.descriptor == &pad_pass__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pad_pass__pack
                     (const PadPass *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pad_pass__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pad_pass__pack_to_buffer
                     (const PadPass *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pad_pass__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PadPass *
       pad_pass__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PadPass *)
     protobuf_c_message_unpack (&pad_pass__descriptor,
                                allocator, len, data);
}
void   pad_pass__free_unpacked
                     (PadPass *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pad_pass__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   video_record__init
                     (VideoRecord         *message)
{
  static VideoRecord init_value = VIDEO_RECORD__INIT;
  *message = init_value;
}
size_t video_record__get_packed_size
                     (const VideoRecord *message)
{
  assert(message->base.descriptor == &video_record__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t video_record__pack
                     (const VideoRecord *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &video_record__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t video_record__pack_to_buffer
                     (const VideoRecord *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &video_record__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VideoRecord *
       video_record__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VideoRecord *)
     protobuf_c_message_unpack (&video_record__descriptor,
                                allocator, len, data);
}
void   video_record__free_unpacked
                     (VideoRecord *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &video_record__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ultra_sonic__init
                     (UltraSonic         *message)
{
  static UltraSonic init_value = ULTRA_SONIC__INIT;
  *message = init_value;
}
size_t ultra_sonic__get_packed_size
                     (const UltraSonic *message)
{
  assert(message->base.descriptor == &ultra_sonic__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ultra_sonic__pack
                     (const UltraSonic *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ultra_sonic__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ultra_sonic__pack_to_buffer
                     (const UltraSonic *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ultra_sonic__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UltraSonic *
       ultra_sonic__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UltraSonic *)
     protobuf_c_message_unpack (&ultra_sonic__descriptor,
                                allocator, len, data);
}
void   ultra_sonic__free_unpacked
                     (UltraSonic *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ultra_sonic__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   message__init
                     (Message         *message)
{
  static Message init_value = MESSAGE__INIT;
  *message = init_value;
}
size_t message__get_packed_size
                     (const Message *message)
{
  assert(message->base.descriptor == &message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t message__pack
                     (const Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t message__pack_to_buffer
                     (const Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Message *
       message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Message *)
     protobuf_c_message_unpack (&message__descriptor,
                                allocator, len, data);
}
void   message__free_unpacked
                     (Message *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pos_point__field_descriptors[2] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(PosPoint, has_x),
    offsetof(PosPoint, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(PosPoint, has_y),
    offsetof(PosPoint, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pos_point__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange pos_point__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pos_point__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PosPoint",
  "PosPoint",
  "PosPoint",
  "",
  sizeof(PosPoint),
  2,
  pos_point__field_descriptors,
  pos_point__field_indices_by_name,
  1,  pos_point__number_ranges,
  (ProtobufCMessageInit) pos_point__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scan_result__field_descriptors[5] =
{
  {
    "position",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ScanResult, n_position),
    offsetof(ScanResult, position),
    &pos_point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "result",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ScanResult, result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "angle",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ScanResult, has_angle),
    offsetof(ScanResult, angle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "picrutesize",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ScanResult, picrutesize),
    &pos_point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "center",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ScanResult, center),
    &pos_point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scan_result__field_indices_by_name[] = {
  2,   /* field[2] = angle */
  4,   /* field[4] = center */
  3,   /* field[3] = picrutesize */
  0,   /* field[0] = position */
  1,   /* field[1] = result */
};
static const ProtobufCIntRange scan_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor scan_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ScanResult",
  "ScanResult",
  "ScanResult",
  "",
  sizeof(ScanResult),
  5,
  scan_result__field_descriptors,
  scan_result__field_indices_by_name,
  1,  scan_result__number_ranges,
  (ProtobufCMessageInit) scan_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pad_pass__field_descriptors[2] =
{
  {
    "pad",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(PadPass, has_pad),
    offsetof(PadPass, pad),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "password",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(PadPass, has_password),
    offsetof(PadPass, password),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pad_pass__field_indices_by_name[] = {
  0,   /* field[0] = pad */
  1,   /* field[1] = password */
};
static const ProtobufCIntRange pad_pass__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pad_pass__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PadPass",
  "PadPass",
  "PadPass",
  "",
  sizeof(PadPass),
  2,
  pad_pass__field_descriptors,
  pad_pass__field_indices_by_name,
  1,  pad_pass__number_ranges,
  (ProtobufCMessageInit) pad_pass__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue video_record__control_type__enum_values_by_number[4] =
{
  { "NULL", "VIDEO_RECORD__CONTROL_TYPE__NULL", 0 },
  { "Start", "VIDEO_RECORD__CONTROL_TYPE__Start", 1 },
  { "Stop", "VIDEO_RECORD__CONTROL_TYPE__Stop", 2 },
  { "Status", "VIDEO_RECORD__CONTROL_TYPE__Status", 3 },
};
static const ProtobufCIntRange video_record__control_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex video_record__control_type__enum_values_by_name[4] =
{
  { "NULL", 0 },
  { "Start", 1 },
  { "Status", 3 },
  { "Stop", 2 },
};
const ProtobufCEnumDescriptor video_record__control_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "VideoRecord.ControlType",
  "ControlType",
  "VideoRecord__ControlType",
  "",
  4,
  video_record__control_type__enum_values_by_number,
  4,
  video_record__control_type__enum_values_by_name,
  1,
  video_record__control_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue video_record__status_type__enum_values_by_number[2] =
{
  { "Recording", "VIDEO_RECORD__STATUS_TYPE__Recording", 0 },
  { "Off", "VIDEO_RECORD__STATUS_TYPE__Off", 1 },
};
static const ProtobufCIntRange video_record__status_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex video_record__status_type__enum_values_by_name[2] =
{
  { "Off", 1 },
  { "Recording", 0 },
};
const ProtobufCEnumDescriptor video_record__status_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "VideoRecord.StatusType",
  "StatusType",
  "VideoRecord__StatusType",
  "",
  2,
  video_record__status_type__enum_values_by_number,
  2,
  video_record__status_type__enum_values_by_name,
  1,
  video_record__status_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor video_record__field_descriptors[5] =
{
  {
    "control",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(VideoRecord, has_control),
    offsetof(VideoRecord, control),
    &video_record__control_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(VideoRecord, has_status),
    offsetof(VideoRecord, status),
    &video_record__status_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "DeviceName",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(VideoRecord, devicename),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "DeviceId",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(VideoRecord, deviceid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Operator",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(VideoRecord, operator_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned video_record__field_indices_by_name[] = {
  3,   /* field[3] = DeviceId */
  2,   /* field[2] = DeviceName */
  4,   /* field[4] = Operator */
  0,   /* field[0] = control */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange video_record__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor video_record__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VideoRecord",
  "VideoRecord",
  "VideoRecord",
  "",
  sizeof(VideoRecord),
  5,
  video_record__field_descriptors,
  video_record__field_indices_by_name,
  1,  video_record__number_ranges,
  (ProtobufCMessageInit) video_record__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ultra_sonic__field_descriptors[1] =
{
  {
    "height",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(UltraSonic, has_height),
    offsetof(UltraSonic, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ultra_sonic__field_indices_by_name[] = {
  0,   /* field[0] = height */
};
static const ProtobufCIntRange ultra_sonic__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ultra_sonic__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UltraSonic",
  "UltraSonic",
  "UltraSonic",
  "",
  sizeof(UltraSonic),
  1,
  ultra_sonic__field_descriptors,
  ultra_sonic__field_indices_by_name,
  1,  ultra_sonic__number_ranges,
  (ProtobufCMessageInit) ultra_sonic__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue message__message_type__enum_values_by_number[5] =
{
  { "NULL", "MESSAGE__MESSAGE_TYPE__NULL", 0 },
  { "ScanResult", "MESSAGE__MESSAGE_TYPE__ScanResult", 1 },
  { "PadPass", "MESSAGE__MESSAGE_TYPE__PadPass", 2 },
  { "VideoRecord", "MESSAGE__MESSAGE_TYPE__VideoRecord", 3 },
  { "UltraSonic", "MESSAGE__MESSAGE_TYPE__UltraSonic", 4 },
};
static const ProtobufCIntRange message__message_type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex message__message_type__enum_values_by_name[5] =
{
  { "NULL", 0 },
  { "PadPass", 2 },
  { "ScanResult", 1 },
  { "UltraSonic", 4 },
  { "VideoRecord", 3 },
};
const ProtobufCEnumDescriptor message__message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Message.MessageType",
  "MessageType",
  "Message__MessageType",
  "",
  5,
  message__message_type__enum_values_by_number,
  5,
  message__message_type__enum_values_by_name,
  1,
  message__message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor message__field_descriptors[2] =
{
  {
    "messagetype",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Message, has_messagetype),
    offsetof(Message, messagetype),
    &message__message_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Message, has_data),
    offsetof(Message, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned message__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = messagetype */
};
static const ProtobufCIntRange message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Message",
  "Message",
  "Message",
  "",
  sizeof(Message),
  2,
  message__field_descriptors,
  message__field_indices_by_name,
  1,  message__number_ranges,
  (ProtobufCMessageInit) message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
